project:
  name: "Amazone Affiliate Automation"
  version: "1.0.0"
  author: "Tannngoc"

app:
  name: Ypee
  version: 1.0.0

database:
  type: sqlite
  path: "app/database/Ypee.db"

services:
  video_resolution: "1080P"
  video_duration: 60
